name: puzzle_test
channels:
  - pytorch
  - nvidia
  - open3d-admin
  - conda-forge
dependencies:
  - python>=3.8, <3.10
  - pip
  - numpy>=1.20
  - pytorch=1.12.1
  - trimesh
  - psutil
  - wandb
  - tqdm
  - imageio
  - opencv-python
  - shapely
  - torchvision=0.13.1
  - open3d
  - networkx